services:
  # Main Service that you want to create a demo
  main:
    image: invoiceshelf/invoiceshelf:latest
    environment:
      - PHP_TZ=UTC
      - TIMEZONE=UTC
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:80
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/InvoiceShelf/database/database.sqlite
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=localhost
      - SANCTUM_STATEFUL_DOMAINS=localhost:80
      - STARTUP_DELAY=
    restart: no

    # The network name should be the same as the one in compose.yaml, so that demo-shelf can find it and access it
    # You should keep this
    networks:
      - demo-shelf_default

networks:
  # The network name should be the same as the one in compose.yaml, so that demo-shelf can find it and access it
  # You should keep this
  demo-shelf_default:
    external: true
